# Generated by Django 4.2.5 on 2023-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('year', models.IntegerField()),
                ('image', models.CharField()),
                ('origin', models.CharField(max_length=200)),
                ('available_items', models.IntegerField()),
            ],
        ),
    ]
